# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(471, 157)
        self.btnLogin = QtWidgets.QPushButton(Form)
        self.btnLogin.setGeometry(QtCore.QRect(290, 110, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName("btnLogin")
        self.btnExit = QtWidgets.QPushButton(Form)
        self.btnExit.setGeometry(QtCore.QRect(380, 110, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.edUsername = QtWidgets.QLineEdit(Form)
        self.edUsername.setGeometry(QtCore.QRect(160, 20, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edUsername.setFont(font)
        self.edUsername.setText("")
        self.edUsername.setObjectName("edUsername")
        self.edPassword = QtWidgets.QLineEdit(Form)
        self.edPassword.setGeometry(QtCore.QRect(160, 60, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edPassword.setFont(font)
        self.edPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edPassword.setObjectName("edPassword")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.edUsername, self.edPassword)
        Form.setTabOrder(self.edPassword, self.btnLogin)
        Form.setTabOrder(self.btnLogin, self.btnExit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login"))
        self.btnLogin.setText(_translate("Form", "Login"))
        self.btnExit.setText(_translate("Form", "Exit"))
        self.label.setText(_translate("Form", "Username"))
        self.label_2.setText(_translate("Form", "Password"))
