# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_pelanggan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 651)
        self.tvList = QtWidgets.QTableView(Form)
        self.tvList.setGeometry(QtCore.QRect(2, 2, 796, 431))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tvList.setFont(font)
        self.tvList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvList.setObjectName("tvList")
        self.edNama = QtWidgets.QLineEdit(Form)
        self.edNama.setGeometry(QtCore.QRect(170, 450, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edNama.setFont(font)
        self.edNama.setObjectName("edNama")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 450, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 500, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnSave = QtWidgets.QPushButton(Form)
        self.btnSave.setGeometry(QtCore.QRect(580, 450, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.btnDelete = QtWidgets.QPushButton(Form)
        self.btnDelete.setGeometry(QtCore.QRect(580, 490, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.btnClear = QtWidgets.QPushButton(Form)
        self.btnClear.setGeometry(QtCore.QRect(580, 530, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.cbActive = QtWidgets.QCheckBox(Form)
        self.cbActive.setGeometry(QtCore.QRect(10, 610, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbActive.setFont(font)
        self.cbActive.setChecked(True)
        self.cbActive.setObjectName("cbActive")
        self.txtedAlamat = QtWidgets.QTextEdit(Form)
        self.txtedAlamat.setGeometry(QtCore.QRect(170, 500, 391, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtedAlamat.setFont(font)
        self.txtedAlamat.setObjectName("txtedAlamat")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.edNama, self.txtedAlamat)
        Form.setTabOrder(self.txtedAlamat, self.btnSave)
        Form.setTabOrder(self.btnSave, self.btnDelete)
        Form.setTabOrder(self.btnDelete, self.btnClear)
        Form.setTabOrder(self.btnClear, self.tvList)
        Form.setTabOrder(self.tvList, self.cbActive)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Nama"))
        self.label_2.setText(_translate("Form", "Alamat"))
        self.btnSave.setText(_translate("Form", "Simpan"))
        self.btnDelete.setText(_translate("Form", "Delete"))
        self.btnClear.setText(_translate("Form", "Clear"))
        self.cbActive.setText(_translate("Form", "Active"))
