# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_ganti_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(590, 132)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 35, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnSave = QtWidgets.QPushButton(Form)
        self.btnSave.setGeometry(QtCore.QRect(480, 35, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.edPassword = QtWidgets.QLineEdit(Form)
        self.edPassword.setGeometry(QtCore.QRect(180, 35, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edPassword.setFont(font)
        self.edPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edPassword.setObjectName("edPassword")
        self.btnClear = QtWidgets.QPushButton(Form)
        self.btnClear.setGeometry(QtCore.QRect(480, 70, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.edConfirmPassword = QtWidgets.QLineEdit(Form)
        self.edConfirmPassword.setGeometry(QtCore.QRect(180, 70, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edConfirmPassword.setFont(font)
        self.edConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edConfirmPassword.setObjectName("edConfirmPassword")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.edPassword, self.btnSave)
        Form.setTabOrder(self.btnSave, self.btnClear)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Password"))
        self.btnSave.setText(_translate("Form", "Simpan"))
        self.btnClear.setText(_translate("Form", "Clear"))
        self.label_3.setText(_translate("Form", "Confirm Password"))
