# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.tvUser = QtWidgets.QTableView(Form)
        self.tvUser.setGeometry(QtCore.QRect(2, 2, 796, 411))
        self.tvUser.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvUser.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvUser.setObjectName("tvUser")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 430, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 460, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 490, 131, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 520, 131, 16))
        self.label_4.setObjectName("label_4")
        self.cbbLevel = QtWidgets.QComboBox(Form)
        self.cbbLevel.setGeometry(QtCore.QRect(160, 520, 281, 22))
        self.cbbLevel.setObjectName("cbbLevel")
        self.cbActive = QtWidgets.QCheckBox(Form)
        self.cbActive.setGeometry(QtCore.QRect(10, 550, 131, 18))
        self.cbActive.setChecked(True)
        self.cbActive.setObjectName("cbActive")
        self.btnSave = QtWidgets.QPushButton(Form)
        self.btnSave.setGeometry(QtCore.QRect(460, 430, 75, 23))
        self.btnSave.setObjectName("btnSave")
        self.btnDelete = QtWidgets.QPushButton(Form)
        self.btnDelete.setGeometry(QtCore.QRect(460, 460, 75, 23))
        self.btnDelete.setObjectName("btnDelete")
        self.edUsername = QtWidgets.QLineEdit(Form)
        self.edUsername.setGeometry(QtCore.QRect(160, 430, 281, 20))
        self.edUsername.setObjectName("edUsername")
        self.edPassword = QtWidgets.QLineEdit(Form)
        self.edPassword.setGeometry(QtCore.QRect(160, 460, 281, 20))
        self.edPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edPassword.setObjectName("edPassword")
        self.edName = QtWidgets.QLineEdit(Form)
        self.edName.setGeometry(QtCore.QRect(160, 490, 281, 20))
        self.edName.setObjectName("edName")
        self.btnClear = QtWidgets.QPushButton(Form)
        self.btnClear.setGeometry(QtCore.QRect(460, 490, 75, 23))
        self.btnClear.setObjectName("btnClear")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.edUsername, self.edPassword)
        Form.setTabOrder(self.edPassword, self.edName)
        Form.setTabOrder(self.edName, self.cbbLevel)
        Form.setTabOrder(self.cbbLevel, self.cbActive)
        Form.setTabOrder(self.cbActive, self.btnSave)
        Form.setTabOrder(self.btnSave, self.btnDelete)
        Form.setTabOrder(self.btnDelete, self.btnClear)
        Form.setTabOrder(self.btnClear, self.tvUser)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Username"))
        self.label_2.setText(_translate("Form", "Password"))
        self.label_3.setText(_translate("Form", "Name"))
        self.label_4.setText(_translate("Form", "Level"))
        self.cbActive.setText(_translate("Form", "Active"))
        self.btnSave.setText(_translate("Form", "Simpan"))
        self.btnDelete.setText(_translate("Form", "Delete"))
        self.btnClear.setText(_translate("Form", "Clear"))
