# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_print.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(801, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.layoutModeSwitch = QtWidgets.QWidget(Form)
        self.layoutModeSwitch.setGeometry(QtCore.QRect(10, 10, 211, 31))
        self.layoutModeSwitch.setObjectName("layoutModeSwitch")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutModeSwitch)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelMode = QtWidgets.QLabel(self.layoutModeSwitch)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelMode.setFont(font)
        self.labelMode.setObjectName("labelMode")
        self.horizontalLayout.addWidget(self.labelMode)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(10, 100, 781, 426))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableView.setFont(font)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.layoutModeComport_2 = QtWidgets.QWidget(Form)
        self.layoutModeComport_2.setGeometry(QtCore.QRect(15, 45, 776, 46))
        self.layoutModeComport_2.setObjectName("layoutModeComport_2")
        self.edSearch = QtWidgets.QLineEdit(self.layoutModeComport_2)
        self.edSearch.setGeometry(QtCore.QRect(73, 9, 691, 36))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.edSearch.setFont(font)
        self.edSearch.setObjectName("edSearch")
        self.labelSearch = QtWidgets.QLabel(self.layoutModeComport_2)
        self.labelSearch.setGeometry(QtCore.QRect(5, 15, 58, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSearch.setFont(font)
        self.labelSearch.setObjectName("labelSearch")
        self.btnPrint = QtWidgets.QPushButton(Form)
        self.btnPrint.setGeometry(QtCore.QRect(10, 535, 781, 56))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnPrint.setFont(font)
        self.btnPrint.setObjectName("btnPrint")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelMode.setText(_translate("Form", "Mode"))
        self.labelSearch.setText(_translate("Form", "Search : "))
        self.btnPrint.setText(_translate("Form", "PRINT"))
import resources_rc
