# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_barang.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.tvBarang = QtWidgets.QTableView(Form)
        self.tvBarang.setGeometry(QtCore.QRect(2, 2, 796, 431))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tvBarang.setFont(font)
        self.tvBarang.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvBarang.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvBarang.setObjectName("tvBarang")
        self.edNamaBarang = QtWidgets.QLineEdit(Form)
        self.edNamaBarang.setGeometry(QtCore.QRect(170, 450, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edNamaBarang.setFont(font)
        self.edNamaBarang.setObjectName("edNamaBarang")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 450, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 500, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.edKategori = QtWidgets.QLineEdit(Form)
        self.edKategori.setGeometry(QtCore.QRect(170, 500, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edKategori.setFont(font)
        self.edKategori.setObjectName("edKategori")
        self.btnSave = QtWidgets.QPushButton(Form)
        self.btnSave.setGeometry(QtCore.QRect(580, 450, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.btnDelete = QtWidgets.QPushButton(Form)
        self.btnDelete.setGeometry(QtCore.QRect(580, 490, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.btnClear = QtWidgets.QPushButton(Form)
        self.btnClear.setGeometry(QtCore.QRect(580, 530, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.cbActive = QtWidgets.QCheckBox(Form)
        self.cbActive.setGeometry(QtCore.QRect(10, 550, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbActive.setFont(font)
        self.cbActive.setChecked(True)
        self.cbActive.setObjectName("cbActive")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.edNamaBarang, self.edKategori)
        Form.setTabOrder(self.edKategori, self.cbActive)
        Form.setTabOrder(self.cbActive, self.btnSave)
        Form.setTabOrder(self.btnSave, self.btnDelete)
        Form.setTabOrder(self.btnDelete, self.btnClear)
        Form.setTabOrder(self.btnClear, self.tvBarang)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Nama Barang"))
        self.label_2.setText(_translate("Form", "Kategori"))
        self.btnSave.setText(_translate("Form", "Simpan"))
        self.btnDelete.setText(_translate("Form", "Delete"))
        self.btnClear.setText(_translate("Form", "Clear"))
        self.cbActive.setText(_translate("Form", "Active"))
